import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.179/build/three.module.js";
import { GLTFLoader } from "https://cdn.jsdelivr.net/npm/three@0.179/examples/jsm/loaders/GLTFLoader.js";
import { InputManager } from "./InputManager.js";
import { TailLampFactory } from "./TailLampFactory.js";

export class Vehicle {
  constructor(game,world){this.game=game;this.scene=game.scene;this.world=world;this.input=new InputManager();this.root=new THREE.Group();this.bodyPivot=new THREE.Group();this.root.add(this.bodyPivot);this.scene.add(this.root);this.model=null;this.progress=0.006;this.laneOffset=0;this.speed=0;this.maxSpeed=31;this.maxReverse=6;this.acceleration=11;this.brakePower=18;this.drag=4.2;this.steer=0;this.finished=false;this.dimensions=new THREE.Vector3(2.2,1.8,4.8);this.headLights=[];this.tailLights=[];this.tailLampShape="bar";this.lastPosition=new THREE.Vector3();}
  async load(url){const gltf=await new GLTFLoader().loadAsync(url);this.model=gltf.scene;const box=new THREE.Box3().setFromObject(this.model);const size=box.getSize(new THREE.Vector3());const scale=2.25/Math.max(size.x,.001);this.model.scale.setScalar(scale);this.model.updateMatrixWorld(true);box.setFromObject(this.model);box.getSize(this.dimensions);this.model.position.y=-box.min.y+.06;this.model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});this.bodyPivot.add(this.model);this.createLights();this.placeAtProgress();}
  update(delta){if(!this.model||this.finished)return;this.updateSpeed(delta);this.updateSteering(delta);this.progress=THREE.MathUtils.clamp(this.progress+this.speed*delta/this.world.length,0,1);this.placeAtProgress(delta);if(this.progress>=.997){this.speed=0;this.finished=true;this.game.ui?.showFinish()}}
  updateSpeed(delta){if(this.input.keys.forward)this.speed+=this.acceleration*delta;if(this.input.keys.backward){if(this.speed>1)this.speed-=this.brakePower*delta;else this.speed-=this.acceleration*.65*delta}if(this.input.keys.brake)this.speed-=Math.sign(this.speed||1)*this.brakePower*delta;if(!this.input.keys.forward&&!this.input.keys.backward&&!this.input.keys.brake)this.speed=THREE.MathUtils.damp(this.speed,0,this.drag,delta);this.speed=THREE.MathUtils.clamp(this.speed,-this.maxReverse,this.maxSpeed)}
  updateSteering(delta){let target=0;if(this.input.keys.left)target=-1;if(this.input.keys.right)target=1;this.steer=THREE.MathUtils.damp(this.steer,target,7,delta);const speedFactor=.35+Math.min(Math.abs(this.speed)/this.maxSpeed,1)*.65;this.laneOffset+=this.steer*delta*8*speedFactor*(this.speed<0?-1:1);const limit=this.world.roadHalfWidth-this.dimensions.x*.48;this.laneOffset=THREE.MathUtils.clamp(this.laneOffset,-limit,limit);if(!target)this.laneOffset=THREE.MathUtils.damp(this.laneOffset,0,.35,delta)}
  placeAtProgress(delta=.016){const pose=this.world.getPose(this.progress,this.laneOffset);this.lastPosition.copy(this.root.position);this.root.position.copy(pose.position);this.root.position.y+=.08;this.root.rotation.y=Math.atan2(pose.tangent.x,pose.tangent.z);const ahead=this.world.getPose(Math.min(1,this.progress+.003),this.laneOffset).position;const behind=this.world.getPose(Math.max(0,this.progress-.003),this.laneOffset).position;const pitch=Math.atan2(ahead.y-behind.y,ahead.distanceTo(behind));this.bodyPivot.rotation.x=THREE.MathUtils.damp(this.bodyPivot.rotation.x,-pitch,7,delta);this.bodyPivot.rotation.z=THREE.MathUtils.damp(this.bodyPivot.rotation.z,-this.steer*.06*Math.min(Math.abs(this.speed)/10,1),6,delta);this.updateLights()}
  createLights(){const w=this.dimensions.x*.32;const front=this.dimensions.z*.48;const rear=-this.dimensions.z*.48;const y=this.dimensions.y*.42;for(const x of [-w,w]){const light=new THREE.SpotLight(0xfff4d5,0,55,THREE.MathUtils.degToRad(24),.65,1.7);light.position.set(x,y,front);const target=new THREE.Object3D();target.position.set(x,y-.65,front+30);this.bodyPivot.add(light,target);light.target=target;this.headLights.push(light)}for(const x of [-w,w]){const lamp=TailLampFactory.create(this.tailLampShape,this.dimensions.x*.22,this.dimensions.y*.10);lamp.position.set(x,y*.82,rear-.03);lamp.rotation.y=Math.PI;this.bodyPivot.add(lamp);const glow=new THREE.PointLight(0xff1f18,0,8,2);glow.position.copy(lamp.position);this.bodyPivot.add(glow);this.tailLights.push({lamp,glow})}}
  setTailLampShape(shape){this.tailLampShape=shape}
  updateLights(){const area=this.world.getArea(this.progress);const dark=area.id>=2;const braking=this.input.keys.brake||this.input.keys.backward;for(const h of this.headLights)h.intensity=dark?32:0;for(const t of this.tailLights){t.lamp.visible=dark||braking;t.glow.intensity=braking?3.2:dark?1.1:0}}
  reset(){this.input.reset();this.progress=.006;this.laneOffset=0;this.speed=0;this.steer=0;this.finished=false;this.placeAtProgress()}
  get speedKmh(){return Math.round(Math.abs(this.speed)*3.6)}
}
